<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Category::truncate();
        (new Category())->insert([
            [
                'id' => 1,
                'name'=> 'Men',
                'slug' =>  Str::slug('Men'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name'=> 'Men Clothing',
                'slug' =>  Str::slug('Men Clothing'),
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name'=> 'Men Traditional Clothing',
                'slug' =>  Str::slug('Men Traditional Clothing'),
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name'=> 'Men Winter Colothing',
                'slug' =>  Str::slug('Men Winter Colothing'),
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name'=> 'Men Innerwear / Sleepwear',
                'slug' =>  Str::slug('Men Innerwear / Sleepwear'),
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name'=> 'Men Shoes',
                'slug' =>  Str::slug('Men Shoes'),
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name'=> 'Men Sandals / Slippers',
                'slug' =>  Str::slug('Men Sandals / Slippers'),
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name'=> 'Men Formal Shoes',
                'slug' =>  Str::slug('Men Formal Shoes'),
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name'=> 'Men Casual Shoes',
                'slug' =>  Str::slug('Men Casual Shoes'),
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name'=> 'Men Sneakers',
                'slug' =>  Str::slug('Men Sneakers'),
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name'=> 'Men Boots',
                'slug' =>  Str::slug('Men Boots'),
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name'=> 'Men Shoe Care',
                'slug' =>  Str::slug('Men Shoe Care'),
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name'=> 'Men Sports Shoes',
                'slug' =>  Str::slug('Men Sports Shoes'),
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name'=> 'Men Watchs',
                'slug' =>  Str::slug('Men Watchs'),
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name'=> 'Men Smart Watches',
                'slug' =>  Str::slug('Men Smart Watches'),
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name'=> 'Men Digital Watches',
                'slug' =>  Str::slug('Men Digital Watches'),
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name'=> 'Men Chronographic Watches',
                'slug' =>  Str::slug('Men Chronographic Watches'),
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name'=> 'Men Analog / Historical Watches',
                'slug' =>  Str::slug('Men Analog / Historical Watches'),
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name'=> 'Men Accessories',
                'slug' =>  Str::slug('Men Accessories'),
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name'=> 'Men Belts / Bags / Purses',
                'slug' =>  Str::slug('Men Belts / Bags / Purses'),
                'parent_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name'=> 'Men Caps / Gloves / Hats',
                'slug' =>  Str::slug('Men Caps / Gloves / Hats'),
                'parent_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name'=> 'Men Wallets / Cardholders',
                'slug' =>  Str::slug('Men Wallets / Cardholders'),
                'parent_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name'=> 'Men Jewellery',
                'slug' =>  Str::slug('Men Jewellery'),
                'parent_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name'=> 'Men Sunglasses',
                'slug' =>  Str::slug('Men Sunglasses'),
                'parent_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name'=> 'Women',
                'slug' =>  Str::slug('Women'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name'=> 'Women Islamic Clothes',
                'slug' =>  Str::slug('Women Islamic Clothes'),
                'parent_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name'=> 'Women Scarfs',
                'slug' =>  Str::slug('Women Scarfs'),
                'parent_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name'=> 'Women Abayas',
                'slug' =>  Str::slug('Women Abayas'),
                'parent_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name'=> 'Women Clothing',
                'slug' =>  Str::slug('Women Clothing'),
                'parent_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name'=> 'Women Traditional Clothing',
                'slug' =>  Str::slug('Women Traditional Clothing'),
                'parent_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name'=> 'Women Winter Colothing',
                'slug' =>  Str::slug('Women Winter Colothing'),
                'parent_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name'=> 'Women Innerwear / Sleepwear',
                'slug' =>  Str::slug('Women Innerwear / Sleepwear'),
                'parent_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name'=> 'Women Shawls',
                'slug' =>  Str::slug('Women Shawls'),
                'parent_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name'=> 'Women Shoes',
                'slug' =>  Str::slug('Women Shoes'),
                'parent_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name'=> 'Women Heels',
                'slug' =>  Str::slug('Women Heels'),
                'parent_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name'=> 'Women Flats / Sandals',
                'slug' =>  Str::slug('Women Flats / Sandals'),
                'parent_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name'=> 'Women Sports Shoes',
                'slug' =>  Str::slug('Women Sports Shoes'),
                'parent_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name'=> 'Women Boots',
                'slug' =>  Str::slug('Women Boots'),
                'parent_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name'=> 'Women Watchs',
                'slug' =>  Str::slug('Women Watchs'),
                'parent_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name'=> 'Women Smart Watches',
                'slug' =>  Str::slug('Women Smart Watches'),
                'parent_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name'=> 'Women Digital Watches',
                'slug' =>  Str::slug('Women Digital Watches'),
                'parent_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name'=> 'Women Chronographic Watches',
                'slug' =>  Str::slug('Women Chronographic Watches'),
                'parent_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name'=> 'Women Analog / Historical Watches',
                'slug' =>  Str::slug('Women Analog / Historical Watches'),
                'parent_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name'=> 'Women Accessories',
                'slug' =>  Str::slug('Women Accessories'),
                'parent_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name'=> 'Women Bags',
                'slug' =>  Str::slug('Women Bags'),
                'parent_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name'=> 'Women Brooches',
                'slug' =>  Str::slug('Women Brooches'),
                'parent_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name'=> 'Women Hats / Caps / Gloves',
                'slug' =>  Str::slug('Women Hats / Caps / Gloves'),
                'parent_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name'=> 'Women Belts / Wallets',
                'slug' =>  Str::slug('Women Belts / Wallets'),
                'parent_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name'=> 'Women Sunglasses',
                'slug' =>  Str::slug('Women Sunglasses'),
                'parent_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name'=> 'Women Jewellery',
                'slug' =>  Str::slug('Women Jewellery'),
                'parent_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name'=> 'Women Jewellery Sets',
                'slug' =>  Str::slug('Women Jewellery Sets'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name'=> 'Women Jewellery Pendants',
                'slug' =>  Str::slug('Women Jewellery Pendants'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name'=> 'Women Jewellery Necklace',
                'slug' =>  Str::slug('Women Jewellery Necklace'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name'=> 'Women Jewellery Ear Rings',
                'slug' =>  Str::slug('Women Jewellery Ear Rings'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name'=> 'Women Jewellery Rings',
                'slug' =>  Str::slug('Women Jewellery Rings'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name'=> 'Women Jewellery Ear Studs',
                'slug' =>  Str::slug('Women Jewellery Ear Studs'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'name'=> 'Women Jewellery Anklets',
                'slug' =>  Str::slug('Women Jewellery Anklets'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name'=> 'Women Jewellery Bracelets',
                'slug' =>  Str::slug('Women Jewellery Bracelets'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name'=> 'Women Jewellery Bangles',
                'slug' =>  Str::slug('Women Jewellery Bangles'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name'=> 'Women Jewellery Nose Pins',
                'slug' =>  Str::slug('Women Jewellery Nose Pins'),
                'parent_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name'=> 'Computers',
                'slug' =>  Str::slug('Computers'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name'=> 'Televisions & Video Devices',
                'slug' =>  Str::slug('Televisions & Video Devices'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'name'=> 'Projectors',
                'slug' =>  Str::slug('Projectors'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'name'=> 'DVD / BluRay Players',
                'slug' =>  Str::slug('DVD / BluRay Players'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'name'=> 'Car Audio / GPS',
                'slug' =>  Str::slug('Car Audio / GPS'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'name'=> 'Security Cameras',
                'slug' =>  Str::slug('Security Cameras'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'name'=> 'Digital Cameras',
                'slug' =>  Str::slug('Digital Cameras'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'name'=> 'Camera Accessories',
                'slug' =>  Str::slug('Camera Accessories'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'name'=> 'Computing',
                'slug' =>  Str::slug('Computing'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'name'=> 'Desktops / Monitors',
                'slug' =>  Str::slug('Desktops / Monitors'),
                'parent_id' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'name'=> 'Laptops',
                'slug' =>  Str::slug('Laptops'),
                'parent_id' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'name'=> 'Printers / Scanners',
                'slug' =>  Str::slug('Printers / Scanners'),
                'parent_id' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'name'=> 'Storage Devices / Accessories',
                'slug' =>  Str::slug('Storage Devices / Accessories'),
                'parent_id' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'name'=> 'Gaming PC / Peripherals',
                'slug' =>  Str::slug('Gaming PC / Peripherals'),
                'parent_id' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'name'=> 'Networking',
                'slug' =>  Str::slug('Networking'),
                'parent_id' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'name'=> 'Video Games',
                'slug' =>  Str::slug('Video Games'),
                'parent_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'name'=> 'Gaming Consoles',
                'slug' =>  Str::slug('Gaming Consoles'),
                'parent_id' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'name'=> 'Board & Card Games',
                'slug' =>  Str::slug('Board & Card Games'),
                'parent_id' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'name'=> 'Gaming Accessories',
                'slug' =>  Str::slug('Gaming Accessories'),
                'parent_id' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'name'=> 'Electronics',
                'slug' =>  Str::slug('Electronics'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'name'=> 'Mobile Phones',
                'slug' =>  Str::slug('Mobile Phones'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'name'=> 'Tablets',
                'slug' =>  Str::slug('Tablets'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'name'=> 'LandLines Sets',
                'slug' =>  Str::slug('LandLines Sets'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'name'=> 'Phone & Tablet Accessories',
                'slug' =>  Str::slug('Phone & Tablet Accessories'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'name'=> 'Access Control',
                'slug' =>  Str::slug('Access Control'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'name'=> 'Attendance Devices',
                'slug' =>  Str::slug('Attendance Devices'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'name'=> 'Security Products',
                'slug' =>  Str::slug('Security Products'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'name'=> 'Fire Fighting Equipment',
                'slug' =>  Str::slug('Fire Fighting Equipment'),
                'parent_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'name'=> 'Fire Alarm System',
                'slug' =>  Str::slug('Fire Alarm System'),
                'parent_id' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'name'=> 'Fire Building Equipment',
                'slug' =>  Str::slug('Fire Building Equipment'),
                'parent_id' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'name'=> 'Lift Style',
                'slug' =>  Str::slug('Lift Style'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'name'=> 'Generators / Power Suppliers',
                'slug' =>  Str::slug('Generators / Power Suppliers'),
                'parent_id' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'name'=> 'Washers / Dryers',
                'slug' =>  Str::slug('Washers / Dryers'),
                'parent_id' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'name'=> 'Refrigerators / Freezers',
                'slug' =>  Str::slug('Refrigerators / Freezers'),
                'parent_id' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'name'=> 'Dishwashers',
                'slug' =>  Str::slug('Dishwashers'),
                'parent_id' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'name'=> 'Heating Items',
                'slug' =>  Str::slug('Heating Items'),
                'parent_id' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'name'=> 'Gysers',
                'slug' =>  Str::slug('Gysers'),
                'parent_id' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'name'=> 'Room Heaters',
                'slug' =>  Str::slug('Room Heaters'),
                'parent_id' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'name'=> 'Kitchen Appliances',
                'slug' =>  Str::slug('Kitchen Appliances'),
                'parent_id' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'name'=> 'Vacuums & Floor Care',
                'slug' =>  Str::slug('Vacuums & Floor Care'),
                'parent_id' => 99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'name'=> 'AC Cooling & Air Appliances',
                'slug' =>  Str::slug('AC Cooling & Air Appliances'),
                'parent_id' => 99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'name'=> 'Personal Care Appliances',
                'slug' =>  Str::slug('Personal Care Appliances'),
                'parent_id' => 99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'name'=> 'Sports',
                'slug' =>  Str::slug('Sports'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'name'=> 'Team Sports',
                'slug' =>  Str::slug('Team Sports'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'name'=> 'Racket Sports',
                'slug' =>  Str::slug('Racket Sports'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'name'=> 'Shoes / Clothing',
                'slug' =>  Str::slug('Shoes / Clothing'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'name'=> 'Exercise / Fitness',
                'slug' =>  Str::slug('Exercise / Fitness'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'name'=> 'Outdoor Activities',
                'slug' =>  Str::slug('Outdoor Activities'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'name'=> 'Sports Bags / Accessories',
                'slug' =>  Str::slug('Sports Bags / Accessories'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'name'=> 'Indoor Games',
                'slug' =>  Str::slug('Indoor Games'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'name'=> 'Outdoor Games',
                'slug' =>  Str::slug('Outdoor Games'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'name'=> 'Travelling - Tourisum',
                'slug' =>  Str::slug('Travelling - Tourisum'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'name'=> 'Sports Nutrition & Suppliments',
                'slug' =>  Str::slug('Sports Nutrition & Suppliments'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'name'=> 'Kids & Toys',
                'slug' =>  Str::slug('Kids and Toys'),
                'parent_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'name'=> 'Kids Watches',
                'slug' =>  Str::slug('Kids Watches'),
                'parent_id' => 114,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'name'=> 'Kids Toys',
                'slug' =>  Str::slug('Kids Toys'),
                'parent_id' => 114,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'name'=> 'Books',
                'slug' =>  Str::slug('Books'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'name'=> 'School Books / Essentials',
                'slug' =>  Str::slug('School Books / Essentials'),
                'parent_id' => 117,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'name'=> 'School Books',
                'slug' =>  Str::slug('School Books'),
                'parent_id' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'name'=> 'School Bags',
                'slug' =>  Str::slug('School Bags'),
                'parent_id' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'name'=> 'School Shoes',
                'slug' =>  Str::slug('School Shoes'),
                'parent_id' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'name'=> 'Water Bottles',
                'slug' =>  Str::slug('Water Bottles'),
                'parent_id' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'name'=> 'Uniforms',
                'slug' =>  Str::slug('Uniforms'),
                'parent_id' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 124,
                'name'=> 'Miscellaneous Items',
                'slug' =>  Str::slug('Miscellaneous Items'),
                'parent_id' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'name'=> 'Books / Magazines',
                'slug' =>  Str::slug('Books / Magazines'),
                'parent_id' => 117,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 126,
                'name'=> 'History',
                'slug' =>  Str::slug('History'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'name'=> 'Politics',
                'slug' =>  Str::slug('Politics'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 128,
                'name'=> 'Science',
                'slug' =>  Str::slug('Science'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 129,
                'name'=> 'Religion',
                'slug' =>  Str::slug('Religion'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 130,
                'name'=> 'Fictions',
                'slug' =>  Str::slug('Fictions'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 131,
                'name'=> 'Novels',
                'slug' =>  Str::slug('Novels'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 132,
                'name'=> 'Poetry',
                'slug' =>  Str::slug('Poetry'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 133,
                'name'=> 'Curiculum Books',
                'slug' =>  Str::slug('Curiculum Books'),
                'parent_id' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 134,
                'name'=> 'E-Books',
                'slug' =>  Str::slug('E-Books'),
                'parent_id' => 117,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 135,
                'name'=> 'History',
                'slug' =>  Str::slug('E History'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 136,
                'name'=> 'Politics',
                'slug' =>  Str::slug('E Politics'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'name'=> 'Science',
                'slug' =>  Str::slug('E Science'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 138,
                'name'=> 'Religion',
                'slug' =>  Str::slug('E Religion'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'name'=> 'Fictions',
                'slug' =>  Str::slug('E Fictions'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 140,
                'name'=> 'Novels',
                'slug' =>  Str::slug('E Novels'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 141,
                'name'=> 'Poetry',
                'slug' =>  Str::slug('E Poetry'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 142,
                'name'=> 'Curiculum Books',
                'slug' =>  Str::slug('E Curiculum Books'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 143,
                'name'=> 'Stationery & Crafts',
                'slug' =>  Str::slug('E Stationery & Crafts'),
                'parent_id' => 134,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 144,
                'name'=> 'Pens',
                'slug' =>  Str::slug('Pens'),
                'parent_id' => 143,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 145,
                'name'=> 'Papers',
                'slug' =>  Str::slug('Papers'),
                'parent_id' => 143,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 146,
                'name'=> 'Registers',
                'slug' =>  Str::slug('Registers'),
                'parent_id' => 143,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 147,
                'name'=> 'Note Books',
                'slug' =>  Str::slug('Note Books'),
                'parent_id' => 143,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 148,
                'name'=> 'Pencils',
                'slug' =>  Str::slug('Pencils'),
                'parent_id' => 143,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 149,
                'name'=> 'Geomatry Boxes',
                'slug' =>  Str::slug('Geomatry Boxes'),
                'parent_id' => 143,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 150,
                'name'=> 'Others',
                'slug' =>  Str::slug('Others'),
                'parent_id' => 143,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 151,
                'name'=> 'Food & Health',
                'slug' =>  Str::slug('Food & Health'),
                'parent_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 152,
                'name'=> 'Health & Beauty',
                'slug' =>  Str::slug('Health & Beauty'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 153,
                'name'=> 'Fragrances',
                'slug' =>  Str::slug('Fragrances'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 154,
                'name'=> 'Hair Care',
                'slug' =>  Str::slug('Hair Care'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 155,
                'name'=> 'Skin Care',
                'slug' =>  Str::slug('Skin Care'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 156,
                'name'=> 'Masks',
                'slug' =>  Str::slug('Masks'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 157,
                'name'=> 'Gloves',
                'slug' =>  Str::slug('Gloves'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 158,
                'name'=> 'Devices',
                'slug' =>  Str::slug('Devices'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 159,
                'name'=> 'Medicines',
                'slug' =>  Str::slug('Medicines'),
                'parent_id' => 151,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
