<script src="{{ asset('seller-assets') }}/js/vendors/datatables/jquery.dataTables.js"></script>
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-bs5/datatables-bootstrap5.js"></script>
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-responsive/datatables.responsive.js"></script>
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-responsive-bs5/responsive.bootstrap5.js"></script>
{{-- <script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-buttons/datatables-buttons.js"></script> --}}
{{-- <script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-buttons/buttons.html5.js"></script>
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-buttons/buttons.print.js"></script> --}}
{{-- <script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-buttons-bs5/buttons.bootstrap5.js"></script> --}}
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-rowgroup/datatables.rowgroup.js"></script>
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-rowgroup-bs5/rowgroup.bootstrap5.js"></script>
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-checkboxes-jquery/datatables.checkboxes.js"></script>
<script src="{{ asset('seller-assets') }}/js/vendors/datatables/datatables-buttons/buttons.server-side.js"></script>
